#cp 1.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c11a.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c11b.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c14a.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c14b.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c17a.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c17b.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c28a.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c28b.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c28c.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c28d.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c28e.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c28f.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c31a.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c31b.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
#cp c3_a.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
#cp c3_b.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c40a.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c40b.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c40c.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c40d.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c41b.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c41d.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c43a.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c43b.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c44d.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c45d.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c46a.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c46b.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c46c.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c46d.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
#cp c4_a.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
#cp c4_b.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
#cp c5_a.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
#cp c5_b.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
#cp c5_c.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
#cp c5_d.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c54a.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c54b.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c54c.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c54d.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c8_a.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c8_b.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c8_c.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp c8_d.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp gSBatpT.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp gZatpT.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp hist_Zi2Z2tot.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp hist_sensi2sens2tot.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp mgSB.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp mgZiZtot.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp mgZsum.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp sens_ithBincontri.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
cp Sens_pTthre.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
#cp Xsec_NNLOhhgF_14_100TeV.tex /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/tex/.
