#cp 1.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c11a.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c11b.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c14a.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c14b.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c17a.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c17b.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c28a.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c28b.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c28c.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c28d.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c28e.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c28f.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c31a.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c31b.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
#cp c3_a.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
#cp c3_b.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c40a.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c40b.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c40c.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c40d.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c41b.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c41d.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c43a.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c43b.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c44d.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c46a.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c46b.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c46c.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c46d.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
#cp c4_a.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
#cp c4_b.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
#cp c5_a.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
#cp c5_b.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
#cp c5_c.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
#cp c5_d.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c54a.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c54b.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c54c.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c54d.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c8_a.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c8_b.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c8_c.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
cp c8_d.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
#cp Xsec_NNLOhhgF_14_100TeV.pdf /home/tamasi/cernbox/phd_thesis/Chapter2/Chapter2Figs/PDF/.
